name: build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create folder
        run: mkdir -p "dist"

      - name: Generate README.txt
        run: cat README.md  > dist/README.txt

      - name: Upload README.txt to S3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-3"
          SOURCE_DIR: "dist"
          DEST_DIR: "dist/$GITHUB_RUN_NUMBER"
      # - name: Upload README.txt
      #   uses: actions/upload-artifact@v2-preview
      #   with:
      #     name: README.txt
      #     path: dist/README.txt
