name: build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create folder
        run: mkdir -p "dist"

      - name: Generate README.txt
        run: cat README.md  > dist/readme.txt

      - name: Upload README.txt
        uses: actions/upload-artifact@v1
        with:
          name: readme.txt
          path: dist/readme.txt
