name: deploy

env:
  AWS_BUCKET: koenoe
  AWS_DEFAULT_REGION: eu-west-3
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Get the version
        run: |
          echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Copy build to production
        run: |
          aws s3 cp s3://koenoe/builds/$VERSION s3://koenoe --recursive --acl public-read --follow-symlinks --cache-control max-age=300
